### ISSUE TITLE
missing categorical.R?

### ISSUE THREAD

**Issue by matt32106** [rohanrao91/Kaggle_Telstra#1]
First of all, thanks for sharing! 
Your source code contains this line but the file is not in your github:
source("./Codes/categorical.R")

Thanks again and good luck for future competitions!

**Comment by rohanrao91** [comment]
Ooppps! Thanks for pointing it out.
I've updated the repo.

**Comment by matt32106** [comment]
Thanks!

Date: Wed, 2 Mar 2016 01:24:17 -0800
From: git.m7.213feed42b.notifications#github.com@ob.0sg.net
To:  reply@reply.github.com
CC: git.m7@xoxy.net
Subject: Re: [Kaggle_Telstra] missing categorical.R? (#1)
of 20)

Ooppps! Thanks for pointing it out.

I've updated the repo.
